# Generated by Django 2.2.4 on 2019-08-11 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='core.Event'),
        ),
        migrations.AlterField(
            model_name='webhookjob',
            name='payload',
            field=models.TextField(),
        ),
    ]
